### ISSUE TITLE
Evaluate hosted services for nodes

### ISSUE THREAD

**Issue by yosriady** [comit-network/app#8]
https://alchemyapi.io/infrastructure

**Comment by bonomat** [comment]
Is this about hosting blockchain nodes? 
If so, we decided for us that we focus on advanced crypto users who are (ready to already) run their own nodes. 
Running a Bitcoin node is not that hard and if someone does not want to run Parity, she can use infura.io

**Comment by yosriady** [comment]
Yes, that's right. 
I was setting up a Bitcoin node locally for the counterparty backend and thought it was too much for normal users. On the Ethereum side, you have a lot of options for hosted nodes, but not the case for the Bitcoin side.

**Comment by yosriady** [comment]
@bonomat Would the advanced users be expected to have their Bitcoin nodes running locally or remotely? What would be the typical node setup for these users?

**Comment by bonomat** [comment]
Our current assumption is that our target users would run their blockchain nodes themselves.  (Our target user is defined as someone who is into blockchain for the _decentralization_ and hence prefers to run their own node. )

Our thinking was that if we change that assumption (e.g. adding 3rd-party hosted nodes) it would mean that one needs to trust that hoster. In that case, we could just add support for blockchain-explorers instead which are free versions of hosted blockchain nodes but should provide all the functionalities we need.

**Comment by yosriady** [comment]
Noted on the decentralization part. 

From what I saw in the SDK so far, you can configure the wallets to use remote nodes. (I could be wrong here.) This means developers are free to do either approach if it suits their use case. Given the current architecture of the SDK, is there anything that would prevent developers from going with a specific approach (e.g. choosing to trust hosted nodes)? 

I figured that the SDK is just an agnostic library for executing cross-chain swaps. What developers build with the COMIT SDK is up to them and their use cases, so they could choose to supply remote node URLs for the Bitcoin / Ethereum wallets if it suits them. For example, some developers who want to build a swap feature may be willing to take that trust-convenience tradeoff for their use case.

**Comment by bonomat** [comment]
Our configurations don't distinguish about _where_ a blockchain node is hosted as long as the provided URL is reachable. 
So all what you said is correct :)
